#!/bin/bash
# VSCode extension bootstrap script
# Run: bash install-extensions.sh

code --install-extension aaron-bond.better-comments
code --install-extension anthropic.claude-code
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EFanZh.graphviz-preview
code --install-extension erd0s.terraform-autocomplete
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension hashicorp.hcl
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension jaimeolivares.yuml
code --install-extension janisdd.vscode-edit-csv
code --install-extension jebbs.plantuml
code --install-extension kortina.vscode-markdown-notes
code --install-extension lextudio.restructuredtext
code --install-extension me-dutour-mathieu.vscode-github-actions
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpp-devtools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.powershell
code --install-extension pieterjongsma.swift-playgrounds
code --install-extension platformio.platformio-ide
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension scala-lang.scala
code --install-extension shahilkumar.docxreader
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Stephanvs.dot
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wso2.choreo
code --install-extension wso2.wso2-platform
code --install-extension yzane.markdown-pdf
code --install-extension zhouronghui.propertylist
code --install-extension zxh404.vscode-proto3
