#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EFanZh.graphviz-preview
code --install-extension lightbend.vscode-sbt-scala
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension ms-python.python
code --install-extension redhat.java
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension Shan.code-settings-sync
code --install-extension Stephanvs.dot
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension zhouronghui.propertylist
